services:
  - type: web
    name: tanavi-admin-portal
    env: static
    rootDir: admin-portal
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
